import type { InsertPlayground } from "@shared/schema";

/**
 * Family destinations across the Des Moines metro.
 *
 * All five kinds live in one table because that is how the decision actually
 * gets made: a parent on a Saturday is choosing between a playground, a splash
 * pad and an indoor option depending on the weather, not browsing categories.
 *
 * The detail fields matter more than the descriptions. Whether a playground is
 * fenced decides if it works with a runner; whether it has shade decides if it
 * works in August; whether there are restrooms decides how long you can stay.
 */
export const seedFamilyPlaces: InsertPlayground[] = [
  // ------------------------------------------------------------- playgrounds
  {
    name: "Gray's Lake Park",
    kind: "playground",
    features: "Lake loop, playground, beach area",
    description:
      "The two-mile paved loop is flat enough for scooters and strollers, and the playground sits near the north parking lot.",
    location: "Gray's Lake, Des Moines",
    ageRange: "All ages",
    searchCount: 90,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Ewing Park",
    kind: "playground",
    features: "Playground, trails, lilac arboretum",
    description:
      "A large south-side park with shaded trails and space to spread out. Quieter than the west-side parks on a weekend.",
    location: "South Side, Des Moines",
    ageRange: "All ages",
    searchCount: 40,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Raccoon River Park",
    kind: "playground",
    features: "Beach, playground, nature lodge, trails",
    description:
      "The metro's most complete family park: a swimming beach, a big playground, and a nature lodge for when the weather turns.",
    location: "West Des Moines",
    ageRange: "All ages",
    searchCount: 80,
    isIndoor: false,
    hasSplashPad: true,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Walnut Creek Park",
    kind: "playground",
    features: "Adventure course, climbing structures",
    description: "Adventure-style climbing equipment aimed at older kids.",
    location: "West Des Moines",
    ageRange: "5-12 years",
    searchCount: 70,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: false,
    hasRestrooms: false,
    isFenced: false,
  },
  {
    name: "Union Park",
    kind: "playground",
    features: "Heritage Carousel, playground, pool",
    description:
      "The restored Heritage Carousel runs summer afternoons and costs a dollar. The playground next to it is shaded most of the day.",
    location: "Highland Park, Des Moines",
    ageRange: "All ages",
    searchCount: 55,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Ashby Park",
    kind: "playground",
    features: "Neighborhood playground, open field",
    description:
      "Beaverdale's main neighborhood playground, walkable from the Beaver Avenue shops.",
    location: "Beaverdale, Des Moines",
    ageRange: "2-10 years",
    searchCount: 35,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Greenwood Park",
    kind: "playground",
    features: "Playground, pond, adjacent to the Art Center",
    description:
      "Next door to the Des Moines Art Center, which makes it an easy pairing: an hour outside, then somewhere free and indoors.",
    location: "Ingersoll, Des Moines",
    ageRange: "All ages",
    searchCount: 45,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Water Works Park",
    kind: "playground",
    features: "Huge open space, trails, amphitheater",
    description:
      "One of the largest urban parks in the country. Good for bikes and kites; the playground areas are small relative to the space.",
    location: "Gray's Lake, Des Moines",
    ageRange: "All ages",
    searchCount: 60,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Prairie Ridge Sports Complex",
    kind: "playground",
    features: "Playground, ball fields, splash pad",
    description:
      "Ankeny's big family complex, with a fenced play area that works well for toddlers.",
    location: "Ankeny",
    ageRange: "All ages",
    searchCount: 50,
    isIndoor: false,
    hasSplashPad: true,
    hasShade: false,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Centennial Park",
    kind: "playground",
    features: "Playground, trails, shelters",
    description: "Waukee's central park, busy with youth sports on weekends.",
    location: "Waukee",
    ageRange: "All ages",
    searchCount: 30,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Walker Johnston Park",
    kind: "playground",
    features: "Playground, pond, trail access",
    description:
      "Urbandale's main park, with trail connections and a fishing pond.",
    location: "Urbandale",
    ageRange: "All ages",
    searchCount: 32,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Terra Park",
    kind: "playground",
    features: "Playground, lake, trails",
    description: "Johnston's lakeside park, with a loop that suits small bikes.",
    location: "Johnston",
    ageRange: "All ages",
    searchCount: 28,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Lions Park",
    kind: "playground",
    features: "Playground, aquatic center next door",
    description: "Small neighborhood park paired with the Urbandale pool.",
    location: "Urbandale",
    ageRange: "2-10 years",
    searchCount: 22,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: false,
    hasRestrooms: true,
    isFenced: false,
  },

  // ------------------------------------------------------------- splash pads
  {
    name: "Ashworth Pool Splash Area",
    kind: "splash_pad",
    features: "Splash area, zero-depth entry pool",
    description:
      "The splash section at Ashworth is separate from the main pool, so small kids get their own space.",
    location: "Ingersoll, Des Moines",
    ageRange: "Under 8",
    searchCount: 65,
    seasonOpen: "Memorial Day to Labor Day",
    isIndoor: false,
    hasSplashPad: true,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Birdland Aquatic Center",
    kind: "splash_pad",
    features: "Splash pad, slides, zero-depth entry",
    description: "North-side aquatic center with a dedicated toddler splash area.",
    location: "Highland Park, Des Moines",
    ageRange: "All ages",
    searchCount: 42,
    seasonOpen: "Memorial Day to Labor Day",
    isIndoor: false,
    hasSplashPad: true,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Clive Aquatic Center",
    kind: "splash_pad",
    features: "Splash pad, lap pool, slides",
    description: "Clive's pool complex, with a shaded splash area for younger kids.",
    location: "Clive",
    ageRange: "All ages",
    searchCount: 38,
    seasonOpen: "Memorial Day to Labor Day",
    isIndoor: false,
    hasSplashPad: true,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Railroad Park Splash Pad",
    kind: "splash_pad",
    features: "Free splash pad in Valley Junction",
    description:
      "Free to use and right by the Fifth Street shops, which makes it an easy stop rather than a whole outing.",
    location: "Historic Valley Junction, West Des Moines",
    ageRange: "Under 10",
    searchCount: 44,
    seasonOpen: "Late May through September",
    isIndoor: false,
    hasSplashPad: true,
    hasShade: false,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Four Mile Aquatic Center",
    kind: "splash_pad",
    features: "Splash pad, pool, slides",
    description: "East-side aquatic center with a separate shallow play area.",
    location: "Pleasant Hill",
    ageRange: "All ages",
    searchCount: 25,
    seasonOpen: "Memorial Day to Labor Day",
    isIndoor: false,
    hasSplashPad: true,
    hasShade: false,
    hasRestrooms: true,
    isFenced: true,
  },

  // ------------------------------------------------------------ indoor play
  {
    name: "Science Center of Iowa",
    kind: "indoor_play",
    features: "Hands-on exhibits, domed theater, skywalk access",
    description:
      "Three floors of hands-on exhibits and the standard answer to a January Saturday. Connects to the skywalk, so you can get there without a coat.",
    location: "Western Gateway, Des Moines",
    ageRange: "All ages",
    searchCount: 120,
    isIndoor: true,
    isSkywalkAccessible: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Altoona Campus",
    kind: "indoor_play",
    features: "Indoor playground, track, courts",
    description:
      "A community rec center with a large indoor playground. Cheap, warm and rarely full on a weekday morning.",
    location: "Altoona",
    ageRange: "Under 12",
    searchCount: 48,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Merle Hay Mall Play Area",
    kind: "indoor_play",
    features: "Free indoor play area",
    description:
      "Free, indoors and open mall hours. Not exciting, but it solves a cold Tuesday.",
    location: "Merle Hay, Des Moines",
    ageRange: "Under 6",
    searchCount: 33,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Get Air Des Moines",
    kind: "indoor_play",
    features: "Trampoline park, foam pits",
    description: "Trampoline park for older kids with energy to burn off.",
    location: "Urbandale",
    ageRange: "5 and up",
    searchCount: 40,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Greater Des Moines Botanical Garden",
    kind: "indoor_play",
    features: "Indoor conservatory dome, children's garden",
    description:
      "The dome stays warm and green all winter, and the children's area is built for touching things.",
    location: "East Village, Des Moines",
    ageRange: "All ages",
    searchCount: 58,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },

  // ---------------------------------------------------------------- libraries
  {
    name: "Des Moines Central Library",
    kind: "library",
    features: "Children's area, storytime, skywalk access",
    description:
      "The Central Library's children's floor runs regular storytimes and is on the skywalk.",
    location: "Western Gateway, Des Moines",
    ageRange: "All ages",
    searchCount: 52,
    isIndoor: true,
    isSkywalkAccessible: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Franklin Avenue Library",
    kind: "library",
    features: "Children's area, weekly storytime",
    description: "Beaverdale's branch, with a well-used children's section.",
    location: "Beaverdale, Des Moines",
    ageRange: "All ages",
    searchCount: 31,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "East Side Library",
    kind: "library",
    features: "Children's area, storytime",
    description: "East-side branch with regular programming for under-fives.",
    location: "East Side, Des Moines",
    ageRange: "All ages",
    searchCount: 24,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "West Des Moines Public Library",
    kind: "library",
    features: "Large children's wing, storytime",
    description:
      "One of the larger children's departments in the metro, with a dedicated play space.",
    location: "West Des Moines",
    ageRange: "All ages",
    searchCount: 46,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Kirkendall Public Library",
    kind: "library",
    features: "Children's area, storytime, maker space",
    description: "Ankeny's library, busy with weekday programming for small kids.",
    location: "Ankeny",
    ageRange: "All ages",
    searchCount: 36,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },

  // ----------------------------------------------------------- nature centers
  {
    name: "Jester Park Nature Center",
    kind: "nature_center",
    features: "Nature center, bison herd, trails",
    description:
      "Free nature center north of the metro, with a bison and elk range a short drive away in the same park.",
    location: "Granger",
    ageRange: "All ages",
    searchCount: 54,
    isIndoor: true,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Blank Park Zoo",
    kind: "nature_center",
    features: "Zoo, indoor and outdoor exhibits",
    description:
      "Iowa's only accredited zoo. Compact enough to do in a morning with small children.",
    location: "South Side, Des Moines",
    ageRange: "All ages",
    searchCount: 95,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: true,
  },
  {
    name: "Chichaqua Bottoms Greenbelt",
    kind: "nature_center",
    features: "Restored wetland, trails, paddling",
    description:
      "A large restored wetland east of the metro. Quiet, and good for older kids who will actually walk.",
    location: "Pleasant Hill",
    ageRange: "6 and up",
    searchCount: 18,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
  {
    name: "Brenton Arboretum",
    kind: "nature_center",
    features: "Arboretum, ponds, open trails",
    description:
      "A quiet arboretum west of the metro with wide mown paths that suit strollers.",
    location: "Dallas Center",
    ageRange: "All ages",
    searchCount: 20,
    isIndoor: false,
    hasSplashPad: false,
    hasShade: true,
    hasRestrooms: true,
    isFenced: false,
  },
];
