import type { NearbyEat } from "@shared/schema";

/**
 * Curated knowledge about the venues we list most often.
 *
 * This is the file that makes an AI-written blurb worth reading. The model can
 * rewrite a description, but it cannot know that the Civic Center has no lot of
 * its own, that Hoyt Sherman's street parking is residential and tight, or that
 * you can reach Wells Fargo Arena from most downtown ramps without going
 * outside. Everything here is passed to the model as context and it is told to
 * use only what it is given.
 *
 * Aliases exist because scraped venue strings are inconsistent: "Des Moines
 * Civic Center", "Civic Center of Greater Des Moines", "Civic Center - Main
 * Stage" all mean one place.
 */
export interface VenueSeed {
  slug: string;
  name: string;
  aliases: string[];
  address?: string;
  neighborhoodSlug?: string;
  lat?: number;
  lng?: number;
  parkingNotes?: string;
  nearbyEats?: NearbyEat[];
  kidNotes?: string;
  isIndoor: boolean;
  isSkywalkAccessible: boolean;
  websiteUrl?: string;
}

export const seedVenues: VenueSeed[] = [
  // ---------------------------------------------- downtown, on the skywalk
  {
    slug: "wells-fargo-arena",
    name: "Wells Fargo Arena",
    aliases: ["wells fargo arena", "iowa events center arena"],
    address: "233 Center St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5904,
    lng: -93.6197,
    parkingNotes:
      "Use the Events Center ramps or any downtown ramp on the skywalk. Street parking near the arena empties slowly after a sellout; the ramps on 3rd and 5th clear faster than the lots right outside.",
    nearbyEats: [
      { name: "Court Avenue", note: "A ten-minute walk south, and where most people end up after a show." },
      { name: "Fong's Pizza", note: "Crab rangoon pizza, five minutes away, usually a wait on event nights." },
    ],
    kidNotes:
      "Family shows use the Center Street entrance, which is less crowded than the main doors. Bag policy is strict.",
    isIndoor: true,
    isSkywalkAccessible: true,
    websiteUrl: "https://www.iowaeventscenter.com/",
  },
  {
    slug: "iowa-events-center",
    name: "Iowa Events Center",
    aliases: ["iowa events center", "hy-vee hall", "community choice credit union convention center"],
    address: "730 3rd St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5904,
    lng: -93.6197,
    parkingNotes:
      "Attached ramps, and the skywalk reaches most of downtown from here. For big trade shows the 3rd Street ramp fills first.",
    nearbyEats: [
      { name: "East Village", note: "A short drive east for anything better than convention food." },
    ],
    isIndoor: true,
    isSkywalkAccessible: true,
    websiteUrl: "https://www.iowaeventscenter.com/",
  },
  {
    slug: "des-moines-civic-center",
    name: "Des Moines Civic Center",
    aliases: [
      "civic center",
      "des moines civic center",
      "civic center of greater des moines",
      "des moines performing arts",
      "stoner theater",
    ],
    address: "221 Walnut St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5861,
    lng: -93.6262,
    parkingNotes:
      "The Civic Center has no lot of its own. The 2nd and Walnut ramp is closest and connects by skywalk; on a sold-out night arrive thirty minutes earlier than you think you need to.",
    nearbyEats: [
      { name: "Centro", note: "Across the street, and the standard pre-show dinner. Book ahead on show nights." },
      { name: "Django", note: "Same block, French brasserie, easier to get into at the bar." },
    ],
    kidNotes:
      "Booster seats are available at coat check for the family series. No under-fours at most evening shows.",
    isIndoor: true,
    isSkywalkAccessible: true,
    websiteUrl: "https://desmoinesperformingarts.org/",
  },
  {
    slug: "science-center-of-iowa",
    name: "Science Center of Iowa",
    aliases: ["science center of iowa", "sciowa", "science center"],
    address: "401 W Martin Luther King Jr Pkwy, Des Moines",
    neighborhoodSlug: "western-gateway",
    lat: 41.5827,
    lng: -93.632,
    parkingNotes: "Free surface lot on site, which is unusual downtown and fills by mid-morning on weekends.",
    nearbyEats: [
      { name: "Fong's Pizza", note: "A short drive, and the easiest family option nearby." },
    ],
    kidNotes:
      "Built for children. Three floors of hands-on exhibits, a domed theater included with admission, and skywalk access so you can arrive without coats in winter.",
    isIndoor: true,
    isSkywalkAccessible: true,
    websiteUrl: "https://www.sciowa.org/",
  },
  {
    slug: "capital-square",
    name: "Capital Square",
    aliases: ["capital square", "capitol square"],
    address: "400 Locust St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5866,
    lng: -93.6252,
    parkingNotes: "Attached ramp, on the skywalk, and quiet on weekends.",
    isIndoor: true,
    isSkywalkAccessible: true,
  },
  {
    slug: "des-moines-central-library",
    name: "Des Moines Central Library",
    aliases: ["central library", "des moines public library central"],
    address: "1000 Grand Ave, Des Moines",
    neighborhoodSlug: "western-gateway",
    lat: 41.5859,
    lng: -93.6323,
    parkingNotes: "Free lot on the west side of the building, plus skywalk access from the Gateway ramps.",
    kidNotes: "The children's floor runs storytimes most weekday mornings and is free.",
    isIndoor: true,
    isSkywalkAccessible: true,
    websiteUrl: "https://www.dmpl.org/",
  },

  // ------------------------------------------ downtown, indoors, off skywalk
  {
    slug: "temple-for-performing-arts",
    name: "Temple for Performing Arts",
    aliases: ["temple for performing arts", "temple theater"],
    address: "1011 Locust St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5866,
    lng: -93.6329,
    parkingNotes: "Metered street parking is free after 6pm downtown. The Gateway ramps are a two-block walk.",
    nearbyEats: [
      { name: "Malo", note: "In the same building. Convenient enough that it books up on event nights." },
    ],
    isIndoor: true,
    isSkywalkAccessible: false,
  },
  {
    slug: "woolys",
    name: "Wooly's",
    aliases: ["wooly's", "woolys", "wooly s"],
    address: "504 E Locust St, Des Moines",
    neighborhoodSlug: "east-village",
    lat: 41.5889,
    lng: -93.6132,
    parkingNotes:
      "East Village street parking is free after 6pm and easier than anywhere downtown proper. The lot behind the building is small.",
    nearbyEats: [
      { name: "Zombie Burger", note: "Two doors down, open late, and the default post-show stop." },
      { name: "Alba", note: "A proper dinner if you are making an evening of it." },
    ],
    kidNotes: "Standing-room music venue. Most shows are 18+ or 21+.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.woolysdm.com/",
  },
  {
    slug: "hoyt-sherman-place",
    name: "Hoyt Sherman Place",
    aliases: ["hoyt sherman place", "hoyt sherman"],
    address: "1501 Woodland Ave, Des Moines",
    neighborhoodSlug: "sherman-hill",
    lat: 41.5901,
    lng: -93.6427,
    parkingNotes:
      "The on-site lot is small and street parking is residential and tight. Arrive early or plan to walk a few blocks.",
    nearbyEats: [
      { name: "Ingersoll Avenue", note: "A short drive west for dinner before a show." },
    ],
    kidNotes: "Historic theater with steep balcony seating; the main floor is easier with small children.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.hoytsherman.org/",
  },
  {
    slug: "iowa-state-capitol",
    name: "Iowa State Capitol",
    aliases: ["iowa state capitol", "state capitol"],
    address: "1007 E Grand Ave, Des Moines",
    neighborhoodSlug: "east-village",
    lat: 41.5912,
    lng: -93.6034,
    parkingNotes: "Free visitor lots on the grounds, plentiful except during the legislative session.",
    kidNotes: "Free guided tours run on the hour most weekdays. The hill outside is the city's best sledding.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.legis.iowa.gov/resources/tourGuide",
  },
  {
    slug: "state-historical-museum",
    name: "State Historical Museum of Iowa",
    aliases: ["state historical museum", "state historical building"],
    address: "600 E Locust St, Des Moines",
    neighborhoodSlug: "east-village",
    lat: 41.5893,
    lng: -93.6104,
    parkingNotes: "Free lot on site.",
    kidNotes: "Free admission, and small enough to do in an hour with young children.",
    isIndoor: true,
    isSkywalkAccessible: false,
  },

  // ------------------------------------------------- indoor, wider metro
  {
    slug: "des-moines-art-center",
    name: "Des Moines Art Center",
    aliases: ["des moines art center", "art center"],
    address: "4700 Grand Ave, Des Moines",
    neighborhoodSlug: "ingersoll",
    lat: 41.5877,
    lng: -93.6852,
    parkingNotes: "Free lot on site, and Greenwood Park has overflow across the road.",
    nearbyEats: [
      { name: "Ingersoll Avenue", note: "Ten minutes east for a proper meal." },
    ],
    kidNotes:
      "Admission is always free, which makes it the reliable rainy-day answer. Greenwood Park's playground is right across the street.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.desmoinesartcenter.org/",
  },
  {
    slug: "xbk-live",
    name: "xBk Live",
    aliases: ["xbk", "xbk live"],
    address: "1159 24th St, Des Moines",
    neighborhoodSlug: "drake",
    lat: 41.5993,
    lng: -93.6592,
    parkingNotes: "Street parking in the Drake neighborhood, free but competitive when the university has an event.",
    nearbyEats: [
      { name: "Mars Cafe", note: "Round the corner, good before an early show." },
    ],
    kidNotes: "Small room, built for listening. Most shows are all-ages but seating is limited.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.xbklive.com/",
  },
  {
    slug: "vibrant-music-hall",
    name: "Vibrant Music Hall",
    aliases: ["vibrant music hall"],
    address: "2938 Grand Prairie Pkwy, Waukee",
    neighborhoodSlug: "waukee",
    lat: 41.6122,
    lng: -93.8858,
    parkingNotes:
      "Large free lot, but one exit onto Grand Prairie Parkway. Leaving after a sellout takes about half an hour.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.vibrantmusichall.com/",
  },
  {
    slug: "val-air-ballroom",
    name: "Val Air Ballroom",
    aliases: ["val air ballroom", "val aire ballroom"],
    address: "301 Ashworth Rd, West Des Moines",
    neighborhoodSlug: "west-des-moines",
    lat: 41.5744,
    lng: -93.7191,
    parkingNotes: "Free lot on site; overflow onto Ashworth Road fills quickly for sold-out shows.",
    nearbyEats: [
      { name: "Valley Junction", note: "Five minutes away, and a better option than anything on the strip." },
    ],
    kidNotes: "Mostly standing room. Check the age policy per show.",
    isIndoor: true,
    isSkywalkAccessible: false,
  },
  {
    slug: "knapp-center",
    name: "Knapp Center",
    aliases: ["knapp center"],
    address: "2601 Forest Ave, Des Moines",
    neighborhoodSlug: "drake",
    lat: 41.6027,
    lng: -93.6555,
    parkingNotes: "Campus lots open to the public on game nights; the Forest Avenue side clears fastest.",
    isIndoor: true,
    isSkywalkAccessible: false,
  },
  {
    slug: "des-moines-playhouse",
    name: "Des Moines Playhouse",
    aliases: ["des moines playhouse", "the playhouse"],
    address: "831 42nd St, Des Moines",
    neighborhoodSlug: "drake",
    lat: 41.5983,
    lng: -93.6801,
    parkingNotes: "Free lot on site.",
    kidNotes: "Runs a dedicated children's theater series with shorter run times.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.dmplayhouse.com/",
  },
  {
    slug: "prairie-meadows",
    name: "Prairie Meadows",
    aliases: ["prairie meadows"],
    address: "1 Prairie Meadows Dr, Altoona",
    neighborhoodSlug: "altoona",
    lat: 41.6444,
    lng: -93.4646,
    parkingNotes: "Free lot, always space.",
    kidNotes: "Casino floor is adults only, but the racetrack apron is open to families on race days.",
    isIndoor: true,
    isSkywalkAccessible: false,
  },
  {
    slug: "greater-des-moines-botanical-garden",
    name: "Greater Des Moines Botanical Garden",
    aliases: ["botanical garden", "greater des moines botanical garden", "botanical center"],
    address: "909 Robert D Ray Dr, Des Moines",
    neighborhoodSlug: "east-village",
    lat: 41.5911,
    lng: -93.6156,
    parkingNotes: "Free lot on site.",
    kidNotes: "The dome stays warm and green all winter, and the children's garden is built for touching things.",
    isIndoor: true,
    isSkywalkAccessible: false,
    websiteUrl: "https://dmbotanicalgarden.com/",
  },

  // ---------------------------------------------------------- outdoor venues
  {
    slug: "principal-park",
    name: "Principal Park",
    aliases: ["principal park"],
    address: "1 Line Dr, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5789,
    lng: -93.6139,
    parkingNotes:
      "Lots around the ballpark, and the Court Avenue ramps are a short walk if those fill. Leaving is easier than arriving.",
    nearbyEats: [
      { name: "Court Avenue", note: "Five minutes on foot for anything better than ballpark food." },
    ],
    kidNotes:
      "The outfield berm is the cheapest seating and the best option with children who will not sit still.",
    isIndoor: false,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.milb.com/iowa",
  },
  {
    slug: "cowles-commons",
    name: "Cowles Commons",
    aliases: ["cowles commons"],
    address: "221 Walnut St, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5866,
    lng: -93.6256,
    parkingNotes: "Use the Civic Center ramps next door. Free street parking after 6pm.",
    kidNotes: "The fountain runs in summer and children are meant to get wet in it.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "pappajohn-sculpture-park",
    name: "Pappajohn Sculpture Park",
    aliases: ["pappajohn sculpture park", "sculpture park"],
    address: "1330 Grand Ave, Des Moines",
    neighborhoodSlug: "western-gateway",
    lat: 41.5862,
    lng: -93.6345,
    parkingNotes: "Free street parking around the park, plus the Gateway ramps a block away.",
    kidNotes: "Open lawn with no shade and no fence. Fine for running, less so on a hot afternoon.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "historic-court-district",
    name: "Historic Court District",
    aliases: ["historic court district", "court avenue district"],
    address: "Court Ave, Des Moines",
    neighborhoodSlug: "court-avenue",
    lat: 41.5856,
    lng: -93.6244,
    parkingNotes:
      "The Court Avenue and 2nd Street ramps beat circling for a meter, especially on farmers market Saturdays.",
    nearbyEats: [
      { name: "El Bait Shop", note: "One of the largest draft lists in the country, right on the strip." },
    ],
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "grays-lake-park",
    name: "Gray's Lake Park",
    aliases: ["gray's lake park", "grays lake park", "gray's lake", "grays lake"],
    address: "2101 Fleur Dr, Des Moines",
    neighborhoodSlug: "grays-lake",
    lat: 41.5673,
    lng: -93.6323,
    parkingNotes: "Free lots at both ends. The north lot fills first on summer evenings.",
    kidNotes:
      "The loop is flat, paved and just under two miles, which works for strollers and small bikes. No fence at the water.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "lauridsen-amphitheater",
    name: "Lauridsen Amphitheater at Water Works Park",
    aliases: ["lauridsen amphitheater", "water works park", "water works"],
    address: "2251 George Flagg Pkwy, Des Moines",
    neighborhoodSlug: "grays-lake",
    lat: 41.5697,
    lng: -93.6486,
    parkingNotes:
      "Parking is on grass in the park and there is one main exit, so leaving after a headliner is slow. Walking in from Gray's Lake is often faster.",
    kidNotes: "Open lawn seating. Bring chairs or a blanket; there is no shade near the stage.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "iowa-state-fairgrounds",
    name: "Iowa State Fairgrounds",
    aliases: ["iowa state fairgrounds", "state fairgrounds", "iowa state fair"],
    address: "3000 E Grand Ave, Des Moines",
    lat: 41.5964,
    lng: -93.5561,
    parkingNotes:
      "Use the official shuttle lots. Neighborhood yards charge more and box you in when everyone leaves at once.",
    kidNotes:
      "Strollers are hard work on fair weekends. The livestock barns are quieter, cooler and more interesting than the food corridor.",
    isIndoor: false,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.iowastatefair.org/",
  },
  {
    slug: "blank-park-zoo",
    name: "Blank Park Zoo",
    aliases: ["blank park zoo"],
    address: "7401 SW 9th St, Des Moines",
    neighborhoodSlug: "south-side",
    lat: 41.5222,
    lng: -93.6216,
    parkingNotes: "Free lot on site.",
    kidNotes: "Compact enough to do in a morning with small children. Several indoor buildings if the weather turns.",
    isIndoor: false,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.blankparkzoo.com/",
  },
  {
    slug: "adventureland",
    name: "Adventureland",
    aliases: ["adventureland"],
    address: "3200 Adventureland Dr, Altoona",
    neighborhoodSlug: "altoona",
    lat: 41.6553,
    lng: -93.4694,
    parkingNotes: "Paid lot on site. Arrive at opening to park close.",
    kidNotes: "Height limits vary widely by ride; check before promising anything to a small child.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "historic-valley-junction",
    name: "Historic Valley Junction",
    aliases: ["historic valley junction", "valley junction"],
    address: "5th St, West Des Moines",
    neighborhoodSlug: "valley-junction",
    lat: 41.573,
    lng: -93.713,
    parkingNotes: "Street parking on Fifth fills fast; the lots one block off are almost always open.",
    nearbyEats: [
      { name: "Fifth Street", note: "The whole street is the food option." },
    ],
    kidNotes: "The Railroad Park splash pad is free and a block from the shops.",
    isIndoor: false,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.valleyjunction.com/",
  },
  {
    slug: "raccoon-river-park",
    name: "Raccoon River Park",
    aliases: ["raccoon river park"],
    address: "2500 Grand Ave, West Des Moines",
    neighborhoodSlug: "west-des-moines",
    lat: 41.5619,
    lng: -93.7592,
    parkingNotes: "Several free lots; the beach lot fills on hot weekends.",
    kidNotes: "Swimming beach, a large playground and a nature lodge for when it rains.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "living-history-farms",
    name: "Living History Farms",
    aliases: ["living history farms"],
    address: "11121 Hickman Rd, Urbandale",
    neighborhoodSlug: "urbandale",
    lat: 41.6198,
    lng: -93.7708,
    parkingNotes: "Free lot on site.",
    kidNotes: "A lot of walking on unpaved paths. Good shoes, and a wagon for anyone under five.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "drake-stadium",
    name: "Drake Stadium",
    aliases: ["drake stadium"],
    address: "2719 Forest Ave, Des Moines",
    neighborhoodSlug: "drake",
    lat: 41.6036,
    lng: -93.6577,
    parkingNotes:
      "Relays week fills every campus lot. Park south of University and walk; the lots nearest the stadium empty slowly.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "brenton-skating-plaza",
    name: "Brenton Skating Plaza",
    aliases: ["brenton skating plaza", "skating plaza"],
    address: "520 Robert D Ray Dr, Des Moines",
    neighborhoodSlug: "downtown",
    lat: 41.5885,
    lng: -93.6187,
    parkingNotes: "Free lot next to the rink, and street parking along Robert D Ray after 6pm.",
    kidNotes: "Skate rental on site down to small sizes. Outdoors, so dress for standing around in the cold.",
    isIndoor: false,
    isSkywalkAccessible: false,
  },
  {
    slug: "jasper-winery",
    name: "Jasper Winery",
    aliases: ["jasper winery"],
    address: "2400 George Flagg Pkwy, Des Moines",
    neighborhoodSlug: "grays-lake",
    lat: 41.5702,
    lng: -93.6479,
    parkingNotes: "Free lot, which overflows onto the grass for the summer concert series.",
    kidNotes: "The summer concerts are family-friendly and on open lawn; bring chairs.",
    isIndoor: false,
    isSkywalkAccessible: false,
    websiteUrl: "https://www.jasperwinery.com/",
  },
];
